
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file
"use strict"
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/client")
exports.discoverMvCount = /*#__PURE__*/ $mkFactory("SELECT\nCOUNT(*)::bigint AS count\nFROM\n(\nSELECT\n1\nFROM\ndiscover_mv r\nWHERE\n(\n$1::TEXT IS NULL\nOR r.tovarni_znacka = $1\n)\nAND (\n$2::TEXT IS NULL\nOR r.obchodni_oznaceni = $2\n)\nAND (\n$3::DATE IS NULL\nOR r.datum_1_registrace >= $3\n)\nAND (\n$4::DATE IS NULL\nOR r.datum_1_registrace <= $4\n)\nAND (\n$5::INT IS NULL\nOR r.rok_vyroby >= $5\n)\nAND (\n$6::INT IS NULL\nOR r.rok_vyroby <= $6\n)\nAND (\n$7::BOOLEAN IS NOT TRUE\nOR r.plne_elektricke_vozidlo = TRUE\n)\nAND (\n$8::BOOLEAN IS NOT TRUE\nOR r.hybridni_vozidlo = TRUE\n)\nAND (\n$9::BOOLEAN IS NOT TRUE\nOR r.imported = TRUE\n)\nAND (\n$10::BOOLEAN IS NOT TRUE\nOR r.removed = TRUE\n)\nAND (\n$11::TEXT IS NULL\nOR r.palivo = $11\n)\n) limited;")
