
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file
"use strict"
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/client")
exports.discoverMvSearch = /*#__PURE__*/ $mkFactory("SELECT\nr.id\nFROM\ndiscover_mv r\nWHERE\n(\n$3::TEXT IS NULL\nOR r.tovarni_znacka = $3\n)\nAND (\n$4::TEXT IS NULL\nOR r.obchodni_oznaceni = $4\n)\nAND (\n$5::DATE IS NULL\nOR r.datum_1_registrace >= $5\n)\nAND (\n$6::DATE IS NULL\nOR r.datum_1_registrace <= $6\n)\nAND (\n$7::INT IS NULL\nOR r.rok_vyroby >= $7\n)\nAND (\n$8::INT IS NULL\nOR r.rok_vyroby <= $8\n)\nAND (\n$9::BOOLEAN IS NOT TRUE\nOR r.plne_elektricke_vozidlo = TRUE\n)\nAND (\n$10::BOOLEAN IS NOT TRUE\nOR r.hybridni_vozidlo = TRUE\n)\nAND (\n$11::BOOLEAN IS NOT TRUE\nOR r.imported = TRUE\n)\nAND (\n$12::BOOLEAN IS NOT TRUE\nOR r.removed = TRUE\n)\nAND (\n$13::TEXT IS NULL\nOR r.palivo = $13\n)\nAND (\n$14::BOOLEAN IS NOT TRUE\nOR r.vin ~ '^[1-9A-HJ-NPR-Z][A-HJ-NPR-Z0-9]{16}$'\n)\nORDER BY\nr.id ASC\nLIMIT\n$1\nOFFSET\n$2;")
