
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file
"use strict"
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/client")
exports.importsWithMatchingVehicle = /*#__PURE__*/ $mkFactory("WITH\nmatched_imports AS (\nSELECT DISTINCT\ni.pcv\nFROM\nimports i\nJOIN registrations r ON i.pcv = r.pcv\nWHERE\n(\ni.country = $3\nOR $3 IS NULL\n) -- Optional country filter\nAND (\n$4::TEXT IS NULL\nOR r.tovarni_znacka = $4\n) -- Optional brand filter\nAND (\n$5::TEXT IS NULL\nOR r.obchodni_oznaceni = $5\n) -- Optional model filter\nORDER BY\ni.pcv -- Ensure deterministic ordering for pagination\nLIMIT\n$1\nOFFSET\n$2\n)\nSELECT\n'imports' AS source,\ni.pcv,\ni.id\nFROM\nimports i\nWHERE\ni.pcv IN (\nSELECT\npcv\nFROM\nmatched_imports\n)\nUNION ALL\nSELECT\n'registrations' AS source,\nr.pcv,\nr.id\nFROM\nregistrations r\nWHERE\nr.pcv IN (\nSELECT\npcv\nFROM\nmatched_imports\n);")
