
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file
"use strict"
exports.importsWithMatchingVehicle = require("./importsWithMatchingVehicle.js").importsWithMatchingVehicle
exports.registrationCountsByYear = require("./registrationCountsByYear.js").registrationCountsByYear
exports.searchBrands = require("./searchBrands.js").searchBrands
exports.searchObchodniOznaceniPerBrand = require("./searchObchodniOznaceniPerBrand.js").searchObchodniOznaceniPerBrand
exports.topCategories = require("./topCategories.js").topCategories
exports.topColors = require("./topColors.js").topColors
exports.topCountriesImports = require("./topCountriesImports.js").topCountriesImports
exports.topFuels = require("./topFuels.js").topFuels
exports.topKinds = require("./topKinds.js").topKinds
