
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file
"use strict"
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/client")
exports.searchObchodniOznaceniPerBrand = /*#__PURE__*/ $mkFactory("SELECT\nobchodni_oznaceni,\ncount\nFROM\nobchodni_oznaceni_per_brand\nWHERE\ntovarni_znacka = $1\nAND (\n$2::TEXT IS NULL\nOR obchodni_oznaceni ILIKE $2 || '%'\n)\nORDER BY\ncount DESC\nLIMIT\n$3;")
