
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file
"use strict"
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/client")
exports.topCountriesImports = /*#__PURE__*/ $mkFactory("SELECT\n*\nFROM\ntop_countries_imports;")
