
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict"
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/library")
exports.topCountriesImports = /*#__PURE__*/ $mkFactory("SELECT\n*\nFROM\ntop_countries_imports;")
