REINDEX INDEX registrations_cislo_orv_idx;

REINDEX INDEX registrations_cislo_tp_idx;

REINDEX INDEX registrations_vin_idx;

REINDEX INDEX idx_vehicle_search_id;

REINDEX INDEX registrations_brand_trgm_idx;

REINDEX INDEX registrations_obchodni_oznaceni_trgm_idx;

REINDEX INDEX registrations_datum_1_registrace_id_idx;

REINDEX INDEX registrations_rok_vyroby_id_idx;

REINDEX INDEX registrations_datum_rok_id_idx;

REINDEX INDEX registrations_hybridni_true_id_idx;

REINDEX INDEX registrations_plne_elektricke_true_id_idx;

REINDEX INDEX registrations_hybridni_datum_id_idx;

REINDEX INDEX registrations_hybridni_rok_vyroby_id_idx;

REINDEX INDEX registrations_plne_elektricke_datum_id_idx;

REINDEX INDEX registrations_plne_elektricke_rok_vyroby_id_idx;
